export const PRODUCT_CATEGORIES = [
  "Laptops",
  "Desktops",
  "Servers",
  "Networking",
  "CCTV",
  "Printers",
  "Software",
  "Components",
  "Accessories",
  "Mobiles",
  "Tablets",
];

export const BRANDS = [
  "Dell",
  "HP",
  "Lenovo",
  "Acer",
  "Asus",
  "Cisco",
  "Hikvision",
  "Dahua",
  "Epson",
  "Canon",
  "Samsung",
  "Apple",
  "Sony",
  "Logitech",
  "TP-Link",
  "D-Link",
  "Netgear",
  "Ubiquiti",
  "Zebra",
  "Honeywell",
];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Karnataka",
  "Tamil Nadu",
  "Telangana",
  "Gujarat",
  "Delhi",
  "Uttar Pradesh",
  "West Bengal",
  "Rajasthan",
  "Kerala",
  "Madhya Pradesh",
  "Punjab",
  "Haryana",
  "Bihar",
  "Odisha",
  "Assam",
  "Chhattisgarh",
  "Jharkhand",
  "Uttarakhand",
  "Goa",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Meghalaya",
  "Nagaland",
  "Sikkim",
];

export const MEMBERSHIP_TIERS = [
  {
    id: "BASIC",
    name: "Basic",
    price: 0,
    description: "Free directory listing for IT dealers.",
    features: [
      "Basic dealer profile",
      "Listed in directory",
      "Email support",
    ],
  },
  {
    id: "STATE",
    name: "State",
    price: 2500,
    description: "State-level membership with enhanced visibility.",
    features: [
      "Verified badge",
      "Priority listing in state",
      "Event discounts",
      "State association updates",
    ],
  },
  {
    id: "PREMIUM",
    name: "Premium",
    price: 7500,
    description: "Premium national visibility and leads.",
    features: [
      "Featured on homepage",
      "Verified badge",
      "Lead notifications",
      "Analytics dashboard",
      "Priority support",
    ],
  },
  {
    id: "NATIONAL",
    name: "National",
    price: 25000,
    description: "Elite national partner status.",
    features: [
      "Top placement in directory",
      "Featured on homepage",
      "Speaking opportunities",
      "National council eligibility",
      "Dedicated account manager",
    ],
  },
];
